<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../installer/SetupBootstrapper/DirectoryDeployment.cs" Link="DirectoryDeployment.cs" />
    <Compile Include="../../installer/SetupBootstrapper/SetupProgress.cs" Link="SetupProgress.cs" />
  </ItemGroup>
</Project>
